/**
 * Markdown formatters for domain store records.
 * Each function generates human-readable markdown for Drive sync.
 * Follows the pattern in markdownFormatter.ts.
 */

import type { MaintenanceTask } from '../types'
import type {
  Vendor, CompletedEvent, FuelDelivery, SepticEvent, WellTest,
  TaxAssessment, TaxPayment, Mortgage, MortgagePayment,
  UtilityAccount, UtilityBill,
} from '../schemas'
import type { CapitalTransaction } from '../types'
import type { InsurancePolicy } from '../types/insurance'
import type { Permit } from '../types/permits'
import type { RoadEvent } from '../types/road'
import type { GeneratorRecord } from '../types/generator'

const footer = () => `\n---\n*Generated by Property Manager · ${new Date().toISOString()}*\n`

function field(label: string, value: unknown): string {
  if (value == null || value === '') return ''
  return `- **${label}:** ${value}\n`
}

// ─── Maintenance ──────────────────────────────────────────────────────────────

export function formatMaintenanceTask(t: MaintenanceTask): string {
  return `# Maintenance: ${t.title}\n\n` +
    field('System', t.systemLabel) +
    field('Category', t.categoryId) +
    field('Due Date', t.dueDate) +
    field('Priority', t.priority) +
    field('Status', t.status) +
    field('Recurrence', t.recurrence) +
    field('Est. Cost', t.estimatedCost != null ? `$${t.estimatedCost}` : null) +
    field('Contractor', t.contractor) +
    field('Source', t.source) +
    field('Notes', t.notes) +
    footer()
}

export function taskFilename(t: MaintenanceTask): string {
  const safe = t.title.replace(/[^a-zA-Z0-9]/g, '_').replace(/__+/g, '_').slice(0, 40)
  return `task_${safe}_${t.id.slice(0, 8)}.md`
}

// ─── Vendor ───────────────────────────────────────────────────────────────────

export function formatVendor(v: Vendor): string {
  return `# Vendor: ${v.name}\n\n` +
    field('Type', v.type) +
    field('Phone', v.phone) +
    field('Email', v.email) +
    field('License', v.license) +
    field('Rating', v.rating) +
    field('Last Used', v.lastUsed) +
    field('Notes', v.notes) +
    footer()
}

export function vendorFilename(v: Vendor): string {
  const safe = v.name.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 40)
  return `vendor_${safe}_${v.id.slice(0, 8)}.md`
}

// ─── Completed Event (Service History) ────────────────────────────────────────

export function formatCompletedEvent(e: CompletedEvent): string {
  return `# Service: ${e.taskTitle}\n\n` +
    field('Date', e.completionDate) +
    field('Category', e.categoryId) +
    field('Cost', e.cost != null ? `$${e.cost}` : null) +
    field('Payment', e.paymentMethod) +
    field('Invoice', e.invoiceRef) +
    field('Contractor', e.contractor) +
    field('Labor Warranty', e.laborWarrantyExpiry) +
    field('Notes', e.notes) +
    footer()
}

export function completedEventFilename(e: CompletedEvent): string {
  const safe = e.taskTitle.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  return `service_${safe}_${e.completionDate}.md`
}

// ─── Capital Transaction ──────────────────────────────────────────────────────

export function formatCapitalTransaction(t: CapitalTransaction): string {
  return `# Capital Transaction\n\n` +
    field('Capital Item', t.capitalItemId) +
    field('Date', t.date) +
    field('Amount', `$${t.amount}`) +
    field('Invoice', t.invoiceRef) +
    field('Notes', t.notes) +
    footer()
}

export function capitalTransactionFilename(t: CapitalTransaction): string {
  return `capital_txn_${t.date}_${t.id.slice(0, 8)}.md`
}

// ─── Fuel Delivery ────────────────────────────────────────────────────────────

export function formatFuelDelivery(d: FuelDelivery): string {
  return `# Fuel Delivery\n\n` +
    field('Date', d.date) +
    field('Fuel Type', d.fuelType) +
    field('Gallons', d.gallons) +
    field('Price/Gal', `$${d.pricePerGallon}`) +
    field('Total', `$${d.totalCost}`) +
    field('Notes', d.notes) +
    footer()
}

export function fuelDeliveryFilename(d: FuelDelivery): string {
  return `fuel_${d.fuelType}_${d.date}_${d.id.slice(0, 8)}.md`
}

// ─── Septic Event ─────────────────────────────────────────────────────────────

export function formatSepticEvent(e: SepticEvent): string {
  return `# Septic Event\n\n` +
    field('Date', e.date) +
    field('Gallons Pumped', e.gallonsPumped) +
    field('Cost', e.cost != null ? `$${e.cost}` : null) +
    field('Technician', e.technician) +
    field('Condition', e.conditionNotes) +
    field('Tech Notes', e.techNotes) +
    field('Next Recommended', e.nextRecommendedDate) +
    footer()
}

export function septicEventFilename(e: SepticEvent): string {
  return `septic_${e.date}_${e.id.slice(0, 8)}.md`
}

// ─── Well Test ────────────────────────────────────────────────────────────────

export function formatWellTest(t: WellTest): string {
  let md = `# Well Test\n\n` +
    field('Date', t.date) +
    field('Lab', t.lab) +
    field('Technician', t.technician) +
    field('Overall Result', t.overallResult) +
    field('Next Test', t.nextTestDate) +
    field('Notes', t.notes)

  if (t.parameters.length > 0) {
    md += '\n## Parameters\n\n| Parameter | Value | Unit | Result |\n|-----------|-------|------|--------|\n'
    for (const p of t.parameters) {
      md += `| ${p.name} | ${p.value} | ${p.unit} | ${p.passFail} |\n`
    }
  }

  return md + footer()
}

export function wellTestFilename(t: WellTest): string {
  return `well_test_${t.date}_${t.id.slice(0, 8)}.md`
}

// ─── Tax Assessment ───────────────────────────────────────────────────────────

export function formatTaxAssessment(a: TaxAssessment): string {
  return `# Tax Assessment — ${a.year}\n\n` +
    field('Year', a.year) +
    field('Assessed Land', `$${a.assessedLand.toLocaleString()}`) +
    field('Assessed Improvement', `$${a.assessedImprovement.toLocaleString()}`) +
    field('Total Assessed', `$${a.totalAssessed.toLocaleString()}`) +
    field('Market Value', a.marketValue != null ? `$${a.marketValue.toLocaleString()}` : null) +
    field('Notes', a.notes) +
    footer()
}

export function taxAssessmentFilename(a: TaxAssessment): string {
  return `tax_assessment_${a.year}_${a.id.slice(0, 8)}.md`
}

// ─── Tax Payment ──────────────────────────────────────────────────────────────

export function formatTaxPayment(p: TaxPayment): string {
  return `# Tax Payment — ${p.year} #${p.installment}\n\n` +
    field('Year', p.year) +
    field('Installment', p.installment) +
    field('Due Date', p.dueDate) +
    field('Paid Date', p.paidDate) +
    field('Amount', `$${p.amount.toLocaleString()}`) +
    field('Penalty', p.penalty != null ? `$${p.penalty}` : null) +
    field('Notes', p.notes) +
    footer()
}

export function taxPaymentFilename(p: TaxPayment): string {
  return `tax_payment_${p.year}_inst${p.installment}_${p.id.slice(0, 8)}.md`
}

// ─── Mortgage ─────────────────────────────────────────────────────────────────

export function formatMortgage(m: Mortgage): string {
  return `# Mortgage: ${m.label}\n\n` +
    field('Lender', m.lender) +
    field('Original Balance', `$${m.originalBalance.toLocaleString()}`) +
    field('Current Balance', `$${m.currentBalance.toLocaleString()}`) +
    field('Interest Rate', `${m.interestRate}%`) +
    field('Term', `${m.termMonths} months`) +
    field('Start Date', m.startDate) +
    field('Monthly Payment', `$${m.monthlyPayment.toLocaleString()}`) +
    field('Escrow', m.escrowAmount != null ? `$${m.escrowAmount}` : null) +
    field('Notes', m.notes) +
    footer()
}

export function mortgageFilename(m: Mortgage): string {
  const safe = m.label.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  return `mortgage_${safe}_${m.id.slice(0, 8)}.md`
}

// ─── Mortgage Payment ─────────────────────────────────────────────────────────

export function formatMortgagePayment(p: MortgagePayment): string {
  return `# Mortgage Payment\n\n` +
    field('Date', p.date) +
    field('Amount', `$${p.amount.toLocaleString()}`) +
    field('Principal', `$${p.principal}`) +
    field('Interest', `$${p.interest}`) +
    field('Escrow', p.escrow != null ? `$${p.escrow}` : null) +
    field('Extra Principal', p.extraPrincipal != null ? `$${p.extraPrincipal}` : null) +
    field('Notes', p.notes) +
    footer()
}

export function mortgagePaymentFilename(p: MortgagePayment): string {
  return `mortgage_payment_${p.date}_${p.id.slice(0, 8)}.md`
}

// ─── Utility Account ──────────────────────────────────────────────────────────

export function formatUtilityAccount(a: UtilityAccount): string {
  return `# Utility Account: ${a.provider}\n\n` +
    field('Type', a.type) +
    field('Provider', a.provider) +
    field('Account #', a.accountNumber) +
    field('Notes', a.notes) +
    footer()
}

export function utilityAccountFilename(a: UtilityAccount): string {
  const safe = a.provider.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  return `utility_acct_${safe}_${a.id.slice(0, 8)}.md`
}

// ─── Utility Bill ─────────────────────────────────────────────────────────────

export function formatUtilityBill(b: UtilityBill): string {
  return `# Utility Bill\n\n` +
    field('Period', `${b.periodStart} to ${b.periodEnd}`) +
    field('Consumption', b.consumption != null ? `${b.consumption} ${b.unit ?? ''}` : null) +
    field('Total Cost', `$${b.totalCost}`) +
    field('Rate/Unit', b.ratePerUnit != null ? `$${b.ratePerUnit}` : null) +
    field('Notes', b.notes) +
    footer()
}

export function utilityBillFilename(b: UtilityBill): string {
  return `utility_bill_${b.periodStart}_${b.id.slice(0, 8)}.md`
}

// ─── Insurance ────────────────────────────────────────────────────────────────

export function formatInsurance(p: InsurancePolicy): string {
  return `# Insurance: ${p.type} — ${p.insurer}\n\n` +
    field('Insurer', p.insurer) +
    field('Policy #', p.policyNumber) +
    field('Type', p.type) +
    field('Status', p.status) +
    field('Premium', p.annualPremium != null ? `$${p.annualPremium}/yr` : null) +
    field('Effective', p.effectiveDate) +
    field('Renewal', p.renewalDate) +
    field('Notes', p.notes) +
    footer()
}

export function insuranceFilename(p: InsurancePolicy): string {
  const safe = p.insurer.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  return `insurance_${p.type}_${safe}_${p.id.slice(0, 8)}.md`
}

// ─── Permit ───────────────────────────────────────────────────────────────────

export function formatPermit(p: Permit): string {
  return `# Permit: ${p.type}\n\n` +
    field('Type', p.type) +
    field('Permit #', p.permitNumber) +
    field('Description', p.description) +
    field('Issuer', p.issuer) +
    field('Issued', p.issuedDate) +
    field('Expires', p.expiryDate) +
    field('Status', p.status) +
    field('Contractor', p.contractor) +
    field('Cost', p.cost != null ? `$${p.cost}` : null) +
    field('Notes', p.notes) +
    footer()
}

export function permitFilename(p: Permit): string {
  const safe = p.type.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 30)
  return `permit_${safe}_${p.id.slice(0, 8)}.md`
}

// ─── Road Event ───────────────────────────────────────────────────────────────

export function formatRoadEvent(e: RoadEvent): string {
  return `# Road: ${e.maintenanceTypeId}\n\n` +
    field('Date', e.date) +
    field('Type', e.maintenanceTypeId) +
    field('Vendor', e.vendor) +
    field('Quantity', e.quantity != null ? `${e.quantity} ${e.unit ?? ''}` : null) +
    field('Area', e.areaDescription) +
    field('Cost', e.cost != null ? `$${e.cost}` : null) +
    field('Notes', e.notes) +
    footer()
}

export function roadEventFilename(e: RoadEvent): string {
  return `road_${e.maintenanceTypeId}_${e.date}_${e.id.slice(0, 8)}.md`
}

// ─── Generator ────────────────────────────────────────────────────────────────

export function formatGenerator(g: GeneratorRecord): string {
  return `# Generator: ${g.name}\n\n` +
    field('Name', g.name) +
    field('Model', g.model) +
    field('Installed', g.installedYear) +
    field('Cumulative Hours', g.cumulativeHours) +
    field('Last Service Hours', g.lastServiceHours) +
    field('Notes', g.notes) +
    footer()
}

export function generatorFilename(g: GeneratorRecord): string {
  const safe = g.name.replace(/[^a-zA-Z0-9]/g, '_').slice(0, 40)
  return `generator_${safe}_${g.id.slice(0, 8)}.md`
}
