/**
 * Default markdown generator for DSL-declared records.
 *
 * Walks `RecordDefinition.fields` and produces a human-readable .md file.
 * Scalar fields render as bullets; `kind: 'array'` fields with
 * `markdownFormat: 'table'` render as a GitHub-flavored markdown table.
 *
 * Record definitions can override this via `def.markdown(record)`.
 */

import type { AnyRecordDefinition, FieldDef } from '../records/_framework'
import {
  visibleIn, slugify, shortId,
  resolveFields, resolveTitle, readFieldValue,
} from '../records/_framework'

const footer = () => `\n---\n*Generated by Property Manager · ${new Date().toISOString()}*\n`

function formatScalar(kind: FieldDef['kind'], value: unknown, unit?: string): string {
  if (value == null || value === '') return ''
  if (kind === 'currency' && typeof value === 'number') {
    return `$${value.toLocaleString()}`
  }
  if (kind === 'number' && typeof value === 'number' && unit) {
    return `${value} ${unit}`
  }
  if (kind === 'boolean') return value ? 'Yes' : 'No'
  return String(value)
}

function renderBullet(field: FieldDef, value: unknown): string {
  const formatted = formatScalar(field.kind, value, field.unit)
  if (!formatted) return ''
  return `- **${field.label}:** ${formatted}\n`
}

function renderArrayTable(field: FieldDef, rows: unknown): string {
  if (!Array.isArray(rows) || rows.length === 0 || !field.of) return ''
  const cols = field.of.filter(f => visibleIn(f, 'markdown'))
  if (cols.length === 0) return ''

  const header = `| ${cols.map(c => c.label).join(' | ')} |`
  const divider = `| ${cols.map(() => '---').join(' | ')} |`
  const body = rows.map(row => {
    const r = row as Record<string, unknown>
    return `| ${cols.map(c => {
      const cell = formatScalar(c.kind, r[c.id], c.unit)
      return cell || ''
    }).join(' | ')} |`
  }).join('\n')

  return `\n## ${field.label}\n\n${header}\n${divider}\n${body}\n`
}

function renderArrayBullets(field: FieldDef, rows: unknown): string {
  if (!Array.isArray(rows) || rows.length === 0) return ''
  const label = field.label
  const items = rows.map(item => {
    if (item == null) return ''
    if (typeof item === 'object') return JSON.stringify(item)
    return String(item)
  }).filter(Boolean)
  if (items.length === 0) return ''
  return `- **${label}:** ${items.join(', ')}\n`
}

/** Generate markdown for one record using the definition's field list. */
export function renderDefaultMarkdown<T extends Record<string, unknown>>(
  def: AnyRecordDefinition,
  record: T,
): string {
  const title = resolveTitle(def, record)
  const fields = resolveFields(def, record)
  let md = `# ${def.label}: ${title}\n\n`

  // First pass: scalar bullets (in declaration order)
  for (const field of fields) {
    if (!visibleIn(field, 'markdown')) continue
    if (field.markdownFormat === 'hidden') continue
    if (field.kind === 'array') continue // handled below
    md += renderBullet(field, readFieldValue(def, record, field.id))
  }

  // Second pass: array fields (tables / bullet lists) appended after scalars
  for (const field of fields) {
    if (!visibleIn(field, 'markdown')) continue
    if (field.kind !== 'array') continue
    if (field.markdownFormat === 'table') {
      md += renderArrayTable(field, readFieldValue(def, record, field.id))
    } else {
      md += renderArrayBullets(field, readFieldValue(def, record, field.id))
    }
  }

  return md + footer()
}

/** Default filename: `<type>_<titleSlug>_<idShort>.md`. */
export function defaultFilename<T extends Record<string, unknown>>(
  def: AnyRecordDefinition,
  record: T,
): string {
  const id = String(record.id ?? '')
  const title = resolveTitle(def, record)
  return `${def.type}_${slugify(title)}_${shortId(id)}.md`
}

/** Render markdown for a record, honoring a custom `def.markdown` override. */
export function renderRecordMarkdown<T extends Record<string, unknown>>(
  def: AnyRecordDefinition,
  record: T,
): string {
  if (def.markdown) return def.markdown(record as never)
  return renderDefaultMarkdown(def, record)
}

/** Resolve filename, honoring a custom `def.filename` override. */
export function recordFilename<T extends Record<string, unknown>>(
  def: AnyRecordDefinition,
  record: T,
): string {
  if (def.filename) return def.filename(record as never)
  return defaultFilename(def, record)
}
