import type { CaptureCategory } from '../data/categories'

/**
 * Generate a safe filename stem for a record.
 * e.g. "generator_Generac_22kW_2026-04-12"
 */
export function formatFileStem(
  category:    CaptureCategory,
  fields:      Record<string, string>,
  capturedAt:  Date,
): string {
  const dateStr = capturedAt.toISOString().slice(0, 10) // YYYY-MM-DD
  const brand   = fields['brand']        ?? fields['unit_type'] ?? ''
  const model   = fields['model']        ?? fields['model_number'] ?? ''
  const parts   = [category.id, brand, model, dateStr].filter(Boolean)

  return parts
    .join('_')
    .replace(/[^a-zA-Z0-9_-]/g, '_')
    .replace(/__+/g, '_')
    .replace(/^_+|_+$/g, '')
}

/**
 * Generate the full Markdown content for a record.
 * This is what gets saved to Google Drive.
 */
export function formatRecord(
  category:       CaptureCategory,
  fields:         Record<string, string>,
  photoFilenames: string[],
  capturedAt:     Date,
): string {
  const lines: string[] = [
    `# ${category.label}`,
    '',
    `**Captured:** ${capturedAt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
    `**Category:** ${category.id}`,
    '',
    '## Specifications',
    '',
  ]

  for (const [key, value] of Object.entries(fields)) {
    if (!value || !value.trim()) continue
    const label = key
      .split('_')
      .map(w => w.charAt(0).toUpperCase() + w.slice(1))
      .join(' ')
    lines.push(`- **${label}:** ${value}`)
  }

  if (lines[lines.length - 1] === '') {
    // no fields were written — add placeholder
    lines.push('_No specifications entered._')
  }

  if (photoFilenames.length > 0) {
    lines.push('', '## Photos', '')
    for (const name of photoFilenames) {
      lines.push(`- [${name}](${name})`)
    }
  }

  lines.push(
    '',
    '---',
    `*Generated by Property Manager · ${capturedAt.toISOString()}*`,
  )

  return lines.join('\n')
}
